name: Publish a New Release
on:
  pull_request:
    branches:
      - 'release/[0-9]+.[0-9]+.*'
    types: [closed]
    

jobs:
  publish_to_npm:
    name: Publish to NPM and GitHub
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Hello World
        run: echo "Hello world!"
