name: Publish a New Release
on:
  pull_request:
    branches: [main]
    types: [closed]
    
# TODO: add condition to fast fail on non-merges and non-release PRs
jobs:
  publish_to_npm:
    name: Publish to NPM and GitHub
    runs-on: ubuntu-latest
    steps:

      # Determine if PR was a merged release PR. If so, publish the new release. Otherwise, do nothing.
      - name: Validate Release PR
        id: validate_pr
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.repository_owner }}
          echo ${{ github.event }}
          echo ${{ toJson(github.event) }}
          echo ${{ github.event.merged }}
          if [ $(grep -E '^release/[0-9]+\.[0-9]+\..+$' <<< '${{ github.head_ref }}') ]
          then
            echo "::set-output name=is_release::true"
          fi

      - name: Hello World
        if: steps.validate_pr.outputs.is_release
        run: echo "Hello world!"

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
