name: Publish a New Release
on:
  pull_request:
    branches: [main]
    types: [closed]
    
jobs:
  publish_to_npm:
    name: Publish to NPM and GitHub
    runs-on: ubuntu-latest
    steps:

      # Determine if PR was a valid merged release PR. If so, publish the new release. Otherwise, do nothing.
      # This is a valid release PR if the following 3 things are true:
      #   1. The head (source) branch of the PR matches the expected "release/x.y.z" pattern
      #   2. The PR has been merged, rather than closed
      #   3. The head (source) repo of the PR is not a fork, or in other words the PR is made from a branch within the main repo
      - name: Validate Release PR
        id: validate_pr
        run: |
          merged=${{ github.event.pull_request.merged }}
          forked=${{ github.event.pull_request.head.repo.fork }}
          echo "Source branch is ${{ github.head_ref }}; merged = $merged; from a fork = $forked"
          if [ $(grep -E '^release/[0-9]+\.[0-9]+\..+$' <<< '${{ github.head_ref }}') ] && [ $merged = true ] && [ $forked = false ]
          then
            echo "::set-output name=is_release::true"
          fi

      # All subsequent steps will no-op if a merged released PR didn't trigger this workflow
      - name: Get Release Metadata
        if: steps.validate_pr.outputs.is_release
        id: metadata
        run: |
          version=$(cut -d'/' -f2 <<< '${{ github.head_ref }}')
          body=${{ github.event.pull_request.body }}
          # tag

          echo "::set-output name=version::$version"

      - name: Checkout Repository
        if: steps.validate_pr.outputs.is_release
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish Release
        if: steps.validate_pr.outputs.is_release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          draft: false
          tag: v${{ steps.metadata.outputs.version }}
