name: Create New Release PR
on:
  workflow_dispatch:
    inputs:
      version:
        description: The semver-compliant version to tag the release with, e.g. 1.2.3, 1.0.0-rc.1
        required: true

jobs:
  create_release_pr:
    name: Create Release PR and Draft Release
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            package-lock.json
            detectors/node/*/node_modules
            metapackages/*/node_modules
            packages/*/node_modules
            plugins/node/*/node_modules
            plugins/web/*/node_modules
            propagators/*/node_modules
          key: ${{ runner.os }}-${{ matrix.container }}-${{ hashFiles('**/package.json') }}

      # Bump versions in all package.json and version.ts files
      - name: Prepare Release
        run: |
          npm install
          npm --no-git-tag-version version ${{ github.event.inputs.version }}
          npx lerna publish ${{ github.event.inputs.version }} --skip-npm --no-git-tag-version --no-push --yes
          npx lerna bootstrap --no-ci

      - name: Update Changelog
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/changelog-update.sh ${{ github.event.inputs.version }}

      # Generates changelog without the "Unreleased" portion for use in release body
      # Newlines must be URL-encoded to render properly in the GitHub UI
      - name: Generate Release Body
        id: generate-changelog
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
        run: |
          description=$(npx lerna-changelog | sed '1,3d')
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}"
          echo "::set-output name=CHANGELOG::$description"

      - name: Create GitHub Release
        id: make-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ github.event.inputs.version }}'
          commitish: main
          release_name: 'v${{ github.event.inputs.version }} Release'
          body: "${{ steps.generate-changelog.outputs.CHANGELOG }}"
          draft: true
          prerelease: false

      - name: Echo release
        run: echo ${{ steps.make-release.outputs.id }}

      # Make PR with version bumps and changelog update. Merging this PR triggers publish workflow.
      # See: https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/.github/workflows/publish.yml
      - name: Create Release PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release/${{ github.event.inputs.version }}
          commit-message: 'chore: ${{ github.event.inputs.version }} release proposal'
          title: 'chore: ${{ github.event.inputs.version }} release proposal'
          body: ${{ steps.make-release.outputs.html_url }}
          delete-branch: true
