name: Release OTel JS Contrib
on:
  workflow_dispatch:
    inputs:
      version:
        description: The semver-compliant version to tag the release with, e.g. 1.2.3, 1.0.0-rc.1
        required: true

jobs:
  publish_otel_contrib:
    name: Publish to GitHub and NPM
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            package-lock.json
            detectors/node/*/node_modules
            metapackages/*/node_modules
            packages/*/node_modules
            plugins/node/*/node_modules
            plugins/web/*/node_modules
            propagators/*/node_modules
          key: ${{ runner.os }}-${{ matrix.container }}-${{ hashFiles('**/package.json') }}

      # Bump versions in all package.json
      - name: Prepare Releasee
        run: |
          npm install
          npx lerna publish ${{ github.event.inputs.version }} --skip-npm --no-git-tag-version --no-push --yes
          npx lerna bootstrap --no-ci

      - name: Update Changelog
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/changelog-update.sh ${{ github.event.inputs.version }}

      # Generates changelog without the "Unreleased" portion
      - name: Generate Changelog
        id: generate-changelog
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx lerna-changelog
          npx lerna-changelog | sed '1,3d'
          echo "::set-output name=CHANGELOG::$(npx lerna-changelog | sed '1,3d')"

      - name: Create GitHub Release
        id: make-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ github.event.inputs.version }}'
          commitish: main
          release_name: 'v${{ github.event.inputs.version }} Release'
          body: ${{ steps.generate-changelog.outputs.CHANGELOG }}
          draft: true
          prerelease: false

      # Make PR with version bumps and changelog update. Merging this PR triggers publish workflow.
      # TODO: add link to second workflow
      - name: Create Release PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release/${{ github.event.inputs.version }}
          commit-message: 'chore: ${{ github.event.inputs.version }} release proposal'
          title: 'chore: ${{ github.event.inputs.version }} release proposal'
          body: ${{ steps.make-release.outputs.html_url }}
          delete-branch: true
